name: "Terraform format, validate, plan check"

on:
  pull_request:
    branches: [ main ]

env:
  TF_CLOUD_ORGANIZATION: "b3nsh-org"
  TF_WORKSPACE: api-driven
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4
          cli_config_credentials_hostname: 'app.terraform.io'
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform Format
        id: format
        run: |
          cd ../
          terraform fmt -check --recursive
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: |
          terraform validate -no-color
          echo "::set-output name=stdout::$(terraform validate -no-color)"
        continue-on-error: true

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        id: plan
        run: |
          terraform plan -no-color -input=false
        continue-on-error: true
      
      - name: generate random delimiter
        run: echo "DELIMITER=$(uuidgen)" >> $GITHUB_ENV

      - name: truncate terraform plan result
        run: |
          echo "PLAN<<${{ env.DELIMITER }}" >> $GITHUB_ENV
          echo '[maybe truncated]' >> $GITHUB_ENV
          tail --bytes=10 <<'${{ env.DELIMITER }}' >> $GITHUB_ENV
          ${{ format('{0}{1}', steps.plan.outputs.stderr, steps.plan.outputs.stdout) }}
          ${{ env.DELIMITER }}
          echo >> $GITHUB_ENV
          echo "${{ env.DELIMITER }}" >> $GITHUB_ENV

      - name: Update Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORMAT: "${{ steps.format.outputs.stdout }}"
          PLAN: "${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `

            ### [api-driven]
            #### Terraform Format and Style 🖌\`${{ steps.format.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

            <details><summary>Show Format</summary>

            \`\`\`\n
            ${process.env.FORMAT}
            \`\`\`

            </details>

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });


      - name: Terraform Format Status
        if: steps.format.outcome == 'failure'
        run: exit 1

      - name: Terraform Validate Status
        if: steps.validate.outcome == 'failure'
        run: exit 1

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
